services:
  - type: web
    name: hule-server
    runtime: node
    plan: free
    buildCommand: npm install && cd server && npm install && npm run build
    startCommand: node dist/server/server/index.js
    envVars:
      - key: NODE_VERSION
        value: 22
